In [116]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor

In [117]:
raw_df = pd.read_csv('DelayedFlights.csv')
raw_df

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,7009710,2008,12,13,6,1250.0,1220,1617.0,1552,DL,...,9.0,18.0,0,N,0,3.0,0.0,0.0,0.0,22.0
1936754,7009717,2008,12,13,6,657.0,600,904.0,749,DL,...,15.0,34.0,0,N,0,0.0,57.0,18.0,0.0,0.0
1936755,7009718,2008,12,13,6,1007.0,847,1149.0,1010,DL,...,8.0,32.0,0,N,0,1.0,0.0,19.0,0.0,79.0
1936756,7009726,2008,12,13,6,1251.0,1240,1446.0,1437,DL,...,13.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1936757,7009727,2008,12,13,6,1110.0,1103,1413.0,1418,DL,...,8.0,11.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [118]:
train, test = train_test_split(raw_df, test_size = 0.5, random_state = 1)

In [119]:
train

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1699602,6294115,2008,11,20,4,1506.0,1405,1820.0,1725,MQ,...,3.0,21.0,0,N,0,55.0,0.0,0.0,0.0,0.0
960306,3223852,2008,6,8,7,1343.0,1334,1434.0,1417,UA,...,7.0,9.0,0,N,0,9.0,0.0,8.0,0.0,0.0
234155,744791,2008,2,26,2,2130.0,1834,2254.0,2000,YV,...,7.0,22.0,0,N,0,174.0,0.0,0.0,0.0,0.0
1765414,6539921,2008,12,26,5,1950.0,1940,2106.0,2105,WN,...,7.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1140705,3801786,2008,7,14,1,1347.0,1338,1704.0,1700,OO,...,11.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491263,1537095,2008,3,6,4,1539.0,1530,1706.0,1654,FL,...,8.0,12.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1840200,6748681,2008,12,23,2,759.0,750,925.0,917,DL,...,6.0,24.0,0,N,0,NaN,NaN,NaN,NaN,NaN
470924,1478136,2008,3,1,6,1840.0,1815,1944.0,1920,WN,...,3.0,9.0,0,N,0,0.0,0.0,0.0,0.0,24.0
491755,1538254,2008,3,7,5,1527.0,1409,1736.0,1635,FL,...,7.0,16.0,0,N,0,0.0,0.0,0.0,0.0,61.0
128037,414451,2008,1,9,3,1129.0,1110,1404.0,1400,MQ,...,5.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [120]:
test

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1750755,6516830,2008,12,19,5,1332.0,1320,1436.0,1430,WN,...,7.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1074983,3577214,2008,6,17,2,1731.0,1720,2013.0,1955,CO,...,8.0,18.0,0,N,0,11.0,0.0,7.0,0.0,0.0
46126,148177,2008,1,27,7,735.0,645,918.0,815,YV,...,4.0,45.0,0,N,0,63.0,0.0,0.0,0.0,0.0
327441,1035260,2008,2,13,3,1333.0,1230,1515.0,1438,9E,...,7.0,15.0,0,N,0,0.0,0.0,0.0,0.0,37.0
1363177,4599044,2008,8,12,2,1359.0,1346,1517.0,1447,FL,...,5.0,15.0,0,N,0,13.0,0.0,17.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222707,4100661,2008,7,21,1,1216.0,1210,1443.0,1450,AA,...,4.0,15.0,0,N,0,NaN,NaN,NaN,NaN,NaN
324475,1025503,2008,2,27,3,1427.0,1420,1601.0,1606,NW,...,11.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1717615,6394259,2008,11,11,2,1236.0,930,1751.0,1450,AA,...,8.0,19.0,0,N,0,181.0,0.0,0.0,0.0,0.0
227263,721616,2008,2,8,5,1416.0,1410,1601.0,1610,XE,...,6.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
495713,1548046,2008,3,20,4,1437.0,1423,1711.0,1633,FL,...,7.0,12.0,0,N,0,0.0,0.0,24.0,0.0,14.0

In [121]:
X_train, X_test, y_train, y_test = train_test_split(train, test, test_size=0.5)

In [122]:
X_train.shape

(484189, 30)

In [123]:
X_test.shape

(484190, 30)

In [124]:
y_train.shape

(484189, 30)

In [125]:
y_test.shape

(484190, 30)

In [126]:
model = LinearRegression().fit(X_train, y_train)
model.score(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'WN'

In [127]:
model = GradientBoostingRegressor(random_state=0).fit(X_train, y_train)
model.score(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'WN'

In [ ]:
model = RandomForestRegressor(random_state=0).fit(X_train, y_train)
model.score(X_train, y_train)
model.score(X_test, y_test)